# Generated by Django 3.2.6 on 2021-12-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default=5, max_length=500),
            preserve_default=False,
        ),
    ]
